
CREATE DATABASE IF NOT EXISTS SALES;
USE SALES;

-- CREACION DE LA TABLA CUSTOMER

CREATE OR REPLACE TABLE CUSTOMER
(
	CODCUS CHAR(8) NOT NULL,
    CUSFIRNAM VARCHAR(60) NOT NULL,
    CUSLASNAM VARCHAR(60) NOT NULL,
    CUSCIT VARCHAR(50) NULL,
    CUSSTA CHAR(2) NULL,
    CUSZIP CHAR(9) NULL,
    CUSBAL DECIMAL(6.2) NULL,
    
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CODCUS)
);

-- CREACION DE LA TABLA EMPLOYEE

CREATE OR REPLACE TABLE EMPLOYEE
(
	CODEMP CHAR(8) NOT NULL,
    EMPFIRNAM VARCHAR(60) NOT NULL,
    EMPLASNAM VARCHAR(60) NOT NULL,
    PHOEMP CHAR(10) NOT NULL,
    EMAEMP VARCHAR(50) NOT NULL,
    
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (CODEMP)
);

-- CREACION DE LA TABLA ORDERTBL

CREATE OR REPLACE TABLE ORDERTBL
(
	CODORDTBL CHAR(8) NOT NULL,
    DATORDTBL DATE NOT NULL,
    CODCUS CHAR(8) NOT NULL,
    CODEMP CHAR(8) NOT NULL,
    
    CONSTRAINT ORDERTBL_PK PRIMARY KEY (CODORDTBL)
);

-- RELACIO DE LA TABLA CUSTOMER A  ORDERTBL
ALTER TABLE ORDERTBL ADD CONSTRAINT CUSTOMER_ORDERTBL_CODCUS FOREIGN KEY (CODCUS) REFERENCES CUSTOMER(CODCUS);
-- RELACIO DE LA TABLA EMPLOYEE A  ORDERTBL
ALTER TABLE ORDERTBL ADD CONSTRAINT EMPLOYEE_ORDERTBL_CODCUS FOREIGN KEY (CODEMP) REFERENCES EMPLOYEE(CODEMP);